[
  {
    "recoverable": false,
    "line": 2,
    "char": 0,
    "content": "for i in",
    "error": "failed to assert: must have a `do` block",
    "error_type": "ASSERTION_FAILED"
  },
  {
    "recoverable": false,
    "line": 12,
    "char": 0,
    "content": "fn name",
    "error": "failed to assert: function must have a do block",
    "error_type": "ASSERTION_FAILED"
  },
  {
    "recoverable": false,
    "line": 9,
    "char": 0,
    "content": "while",
    "error": "failed to assert: must have two children, got [\"true\"]",
    "error_type": "ASSERTION_FAILED"
  }
]
